apiVersion: v1
kind: Service
metadata:
  name: agricnxedge-api
  namespace: agricnxedge
  labels:
    app: agricnxedge-api
spec:
  type: ClusterIP
  selector:
    app: agricnxedge-api
  ports:
    - name: http
      port: 80
      targetPort: http
